# Generated by Django 3.0.7 on 2021-05-25 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('time_won', models.DateTimeField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('clue1Reached', models.DateTimeField(null='True')),
                ('clue2Reached', models.DateTimeField(null='True')),
                ('clue3Reached', models.DateTimeField(null='True')),
                ('clue4Reached', models.DateTimeField(null='True')),
                ('clue5Reached', models.DateTimeField(null='True')),
                ('clue6Reached', models.DateTimeField(null='True')),
                ('clue7Reached', models.DateTimeField(null='True')),
                ('clue8Reached', models.DateTimeField(null='True')),
                ('clue9Reached', models.DateTimeField(null='True')),
                ('clue10Reached', models.DateTimeField(null='True')),
                ('clue11Reached', models.DateTimeField(null='True')),
                ('clue12Reached', models.DateTimeField(null='True')),
                ('clue13Reached', models.DateTimeField(null='True')),
                ('clue14Reached', models.DateTimeField(null='True')),
                ('clue15Reached', models.DateTimeField(null='True')),
                ('clue16Reached', models.DateTimeField(null='True')),
                ('clue17Reached', models.DateTimeField(null='True')),
                ('clue18Reached', models.DateTimeField(null='True')),
                ('clue19Reached', models.DateTimeField(null='True')),
                ('clue20Reached', models.DateTimeField(null='True')),
                ('clue21Reached', models.DateTimeField(null='True')),
                ('clue22Reached', models.DateTimeField(null='True')),
                ('clue23Reached', models.DateTimeField(null='True')),
                ('clue24Reached', models.DateTimeField(null='True')),
                ('clue25Reached', models.DateTimeField(null='True')),
                ('clue26Reached', models.DateTimeField(null='True')),
                ('clue27Reached', models.DateTimeField(null='True')),
                ('clue28Reached', models.DateTimeField(null='True')),
                ('clue29Reached', models.DateTimeField(null='True')),
                ('clue30Reached', models.DateTimeField(null='True')),
                ('clue31Reached', models.DateTimeField(null='True')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clueReached', models.IntegerField(default=1)),
                ('clue1Reached', models.DateTimeField(blank=True, null=True)),
                ('clue2Reached', models.DateTimeField(blank=True, null=True)),
                ('clue3Reached', models.DateTimeField(blank=True, null=True)),
                ('clue4Reached', models.DateTimeField(blank=True, null=True)),
                ('clue5Reached', models.DateTimeField(blank=True, null=True)),
                ('clue6Reached', models.DateTimeField(blank=True, null=True)),
                ('clue7Reached', models.DateTimeField(blank=True, null=True)),
                ('clue8Reached', models.DateTimeField(blank=True, null=True)),
                ('clue9Reached', models.DateTimeField(blank=True, null=True)),
                ('clue10Reached', models.DateTimeField(blank=True, null=True)),
                ('clue11Reached', models.DateTimeField(blank=True, null=True)),
                ('clue12Reached', models.DateTimeField(blank=True, null=True)),
                ('clue13Reached', models.DateTimeField(blank=True, null=True)),
                ('clue14Reached', models.DateTimeField(blank=True, null=True)),
                ('clue15Reached', models.DateTimeField(blank=True, null=True)),
                ('clue16Reached', models.DateTimeField(blank=True, null=True)),
                ('clue17Reached', models.DateTimeField(blank=True, null=True)),
                ('clue18Reached', models.DateTimeField(blank=True, null=True)),
                ('clue19Reached', models.DateTimeField(blank=True, null=True)),
                ('clue20Reached', models.DateTimeField(blank=True, null=True)),
                ('clue21Reached', models.DateTimeField(blank=True, null=True)),
                ('clue22Reached', models.DateTimeField(blank=True, null=True)),
                ('clue23Reached', models.DateTimeField(blank=True, null=True)),
                ('clue24Reached', models.DateTimeField(blank=True, null=True)),
                ('clue25Reached', models.DateTimeField(blank=True, null=True)),
                ('clue26Reached', models.DateTimeField(blank=True, null=True)),
                ('clue27Reached', models.DateTimeField(blank=True, null=True)),
                ('clue28Reached', models.DateTimeField(blank=True, null=True)),
                ('clue29Reached', models.DateTimeField(blank=True, null=True)),
                ('clue30Reached', models.DateTimeField(blank=True, null=True)),
                ('clue31Reached', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact', models.CharField(blank='True', default=' ', max_length=15, null='True')),
                ('teammate_name1', models.CharField(blank='True', default=' ', max_length=50, null='True')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
