# Generated by Django 3.0.7 on 2021-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210917_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teammate_name2',
            field=models.CharField(blank='True', default=' ', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teammate_name3',
            field=models.CharField(blank='True', default=' ', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teammate_name4',
            field=models.CharField(blank='True', default=' ', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teammate_name5',
            field=models.CharField(blank='True', default=' ', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
