# Generated by Django 3.0.7 on 2021-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_no', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('ans1', models.CharField(max_length=300)),
                ('ans2', models.CharField(max_length=300, null='True')),
            ],
        ),
    ]
