# Generated by Django 3.0.7 on 2021-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clues', '0002_descqtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='descqtn',
            name='q_heading',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
